version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30-node
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: jars-{{ checksum "android/app/build.gradle" }}-{{ checksum "android/build.gradle" }}

      - run:
          name: Download Dependencies
          command: |
            yarn install

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "android/app/build.gradle" }}-{{ checksum "android/build.gradle" }}

      - run:
          name: Run Tests
          command: |
            yarn test

      - run:
          name: Build Android
          command: |
            cd android && ./gradlew assembleRelease

      - store_artifacts:
          path: android/app/build/outputs/**/*.apk
          destination: /artifacts

  deploy:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Deploy to Firebase
          command: |
            yarn global add firebase-tools
            firebase login --no-interactive
            firebase deploy --token $FIREBASE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
